name: Rajmahal and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --no-progress

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Assets
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan key:generate
          npm run build

      - name: Set Directory Permissions
        run: chmod -R 775 storage bootstrap/cache

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy PHP to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd /home/u195346316/domains/mongmatubbar.com/public_html/rajmahal
            git pull
            composer install --no-dev --prefer-dist --no-interaction --no-progress
            chmod -R 775 storage bootstrap/cache

      - name: Copy Build Files to Target Server
        run: |
          rsync -r -e "ssh -p ${{ secrets.SSH_PORT }}" ${{ github.workspace }}/public/build/ \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:domains/mongmatubbar.com/public_html/rajmahal/public/build
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
